# Generated by Django 5.1.3 on 2024-11-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='finished_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
